skorokithakis/catt

catt/controllers.py
Greetings! Just a little improvement to make catt faster
=> Speed up casting by not killing apps known to be nonblocking

catt/http_server.py
Hi. Just a little fix to get things working with python3.
=> fix: Add python3 compatible imports

catt/cli.py, catt/controllers.py, tests/test_catt.py
Hi. So here's part 1 of the solution to https://github.com/skorokithakis/catt/issues/5 (config still to come).
I am not very good friends with click, so I hope my implementation is somewhat correct.
=> feat: Add user selectable CC device

catt/cli.py
Hi. I have made this little handy custom parameter type (as described [here](http://click.pocoo.org/6/parameters/#implementing-custom-types)), that enables the user to use normal time descriptions when using `seek`, `ffwd` or `rewind`. 
F.ex. `catt seek 01:14:20`.
Something like `catt ffwd 500` would still work as is does now.
=> feat: Add custom time type for seek functions

catt/cli.py
=> fix: Change volume description

catt/cli.py, catt/controllers.py
Looks nicer and works as expected.
.......and that should be the end of this series of PR's.
=> fix: Cleanup in controllers / cli.

catt/cli.py, catt/controllers.py
Less annoying and just as useful.
=> fix: Replace connection message with more useful error message.

catt/cli.py
This PR is a bit of a POC at this point, but it seems to be working rather well.
Note that I have used the name `"defaults"` for the default section, as the values from `"DEFAULT"` are read into all sections, which is not useful in this scenario.
`main()` does not look too pretty, so if you know how to make it more concise then that would be great.
=> feat: Add aliases to config.

setup.py
=> fix: Freeze requirements until #12 is sorted

catt/controllers.py
As discussed in #23.
Tested with youtube, bandcamp, nfl and generic, but probably needs a bit more testing.
EDIT: ready to merge
=> fix: Better handling of playlists

setup.py
Some of the important extractors have changed recently, so best to update this.
=> Bump youtube-dl requirement

catt/controllers.py
=> feat: Make scan fail when no cc's are found

README.rst
=> docs: Add missing word in config section

catt/cli.py, catt/controllers.py, catt/http_server.py
Hi. Just a bit of tidying up here. A few variable names that were too short or redefined something builtin or from outer scope. Fixed that. Also added quotes to device name in error message, that could otherwise be confusing.
I've tested all functionality and everything seems to work.
=> Summer cleaning

AUTHORS.rst, LICENSE, catt/cli.py, catt/controllers.py, catt/stream_info.py, catt/youtube.py, tests/test_catt.py
~~Use [this fork of pychromecast](https://github.com/theychx/pychromecast) with this branch.~~
In case you're wondering, the controller does unfortunately not support dumping a yt playlist in one go (this works when casting from my Android phone), thus the lame method of adding videos one by one.
=> [WIP] YouTube Queue support

catt/cli.py, catt/stream_info.py
fixes #41
Now we just need to know what to look for in `cast.model_name` (or whatever). Until then, this PR will effectively force 1080p on everything.
=> Add preliminary cc type detection

catt/cli.py, catt/stream_info.py
=> Improve cc type detection

README.rst
Seems a bit superflous anyway (if it existed :smiley: ).
=> Remove readthedocs entry from readme

README.rst
A little convenience for users.
=> Update readme with link to supported sites page

catt/cli.py, catt/controllers.py, catt/stream_info.py, catt/youtube.py, setup.cfg, tests/test_catt.py
Hi
So while I did the YouTube stuff, I realized that ```catt``` would turn into a mess sooner rather than later, if we were to just continue to latch new functionality from different controllers onto existing code. So I propose this design, that tries to make the capabilities (or lack thereof) of any controller, transparent to the cli. Let me know what you think.
List of things that are not implemented yet:
+ ~~Playing first item of playlist, when controller does not support playlist playback.~~
+ ~~Feedback to user when casting YouTube playlists (mass-adding videos).~~
+ ~~Warnings to users, trying to use YouTube functionality with audio devices.~~
+ ~~Tests are of course broken.~~
+ Other stuff I forgot about.
+ ~~Add docstrings.~~
=> [WIP] Controllers refactor

catt/stream_info.py
Easier to read and maintain if/when a lot of format hacks are added.
=> Update and restructure format hacks

catt/cli.py, catt/stream_info.py
Something I've wanted/needed for a long time, but were too lazy to implement.
=> Add ability to receive path/url from stdin

catt/cli.py, catt/controllers.py, catt/stream_info.py
=> Add title and thumbnail to buffering screen

catt/controllers.py
Now with title and volume info.
=> Make status command more useful

catt/cli.py, catt/controllers.py, catt/stream_info.py
Hello!
A few improvements/fixes:
+ Further scrutinize input in ```cli.add``` so we fail instead of crashing, when f.ex. the user tries to add a youtube playlist url.
+ A few special kinds of urls (like yt channel urls) are now re-processed, so those can be played as yt playlist urls.
+ Fixes #68 
+ Proper volume display in python 2
I've put this branch through my testing scheme in BOTH :smile: py2 and 3. I somehow managed to convince myself that I had already done that, but apparently I didn't.
The ```2.0.0``` release of pychromecast (without py2 support) is now out FYI.
=> Misc improvements/fixes for final Python 2 release

README.rst
=> Update README with config file location on Windows

catt/stream_info.py, setup.py
Hopefully we can fix #73 before releasing ```0.5.5```
=> [WIP] Py2 final release

.travis.yml, catt/cli.py, catt/controllers.py, catt/http_server.py, setup.py, tests/test_catt.py, tox.ini
As discussed in #57 (CI failed because of weird 403's from vimeo, thus the junk commits).
=> Remove py2 compat code

catt/cli.py, catt/controllers.py
=> Add force default option to cast command

catt/http_server.py, catt/stream_info.py
Howdy
Forgot about ```stream_info``` and ```http_server``` also using ```os```. I've included the local file casting fix (removal of "Accept-Ranges" header).
Looking forward (short-term), I'm honestly more keen on working on the save/restore stuff right now. So if it's ok with you, I'd be cool if you could make a ```0.6.0``` release after this is merged.
Fixes #73
=> More pathlib fun

catt/cli.py, catt/controllers.py
Just a little tweak so we don't kill runnnig cc sessions on certain type of fails.
..and a fix for a bug from the previous PR.
=> Improve kill

catt/cli.py, catt/stream_info.py
Gave me an opportunity to get rid of the lame ```first_entry``` stuff in ```StreamInfo```.
Closes #83
=> Play random playlist entry / StreamInfo improvements

catt/cli.py, catt/controllers.py
=> Add color to warning messages

catt/cli.py, catt/controllers.py
=> Improve save/restore

catt/cli.py, catt/controllers.py, catt/util.py
I forgot to set the ```err``` flag in the color part of warning messages in my previous effort, so I figured that I might as well do as you suggested.
=> Add warning function

README.rst
@skorokithakis Thanks so much for this tool!
=> Use a more educational example Youtube link

catt/cli.py, catt/controllers.py
..so we can put additional code after the main clause in cli.cast.
=> Refactor playlist capability handling slightly

README.rst, catt/cli.py
Minor things I mentioned on https://github.com/skorokithakis/catt/pull/103
=> more changes related to cast_url becoming cast_site

catt/cli.py, catt/stream_info.py
An attempt to make things a bit simpler.
=> Another StreamInfo refactor

catt/cli.py, catt/controllers.py
=> Add missing dots to messages

catt/controllers.py
..otherwise "playing" would never be set.
=> Fix silly mistake in MediaStatusListener constructor

catt/cli.py, catt/controllers.py, catt/stream_info.py
Some of the websites that youtube-dl supports requires login. Read the catt's code but haven't found any solution or workaround for login, so I implemented it.
=> YoutubeDL options implemented

catt/controllers.py
A few fixes, so we have correct behaviour of ```status``` when casting images. Also ```DashCastController``` now fails with the control commands it doesn't support.
=> Minor image casting / Dashcast fixes

catt/cli.py, catt/controllers.py, catt/stream_info.py
=> Very late spring cleaning

catt/api.py, catt/controllers.py
Howdy
Here's my attempt at implementing some of what we agreed on.
I realize that it might be more elegant to implement the dynamic creation of cast and cast_controller with some kind of metaclass, so not all "transport" methods have to call ```_create_controller```. I couldn't figure out how to accomplish that though, so suggestions are welcome.
=> First api mockup

catt/api.py, catt/cli.py, catt/controllers.py, examples/accidents.py
The prototype is now a bit more complete. I've reimplemented the example.
I've also begun a quest to get rid of as many of the click exception raise statements as possible, now that ```controllers.py``` do not only have to cater to ```cli.py```.
=> More api stuff

.pre-commit-config.yaml, catt/http_server.py, catt/youtube.py
This implements `Range` header support and allows seeking.
=> Allow seeking on local files (fixes #130)

catt/api.py, catt/controllers.py, setup.py
Let's try this again :smile: , and then merge your changes into ```api-develop``` before doing the final merge.
=> First attempt at fixing 404 issues

catt/api.py, catt/cli.py, catt/controllers.py, catt/stream_info.py, catt/youtube.py, examples/accidents.py, setup.py
This is stable enough to merge into master.
I have a slew of minor PR's, I'd like to have merged after this, before we make a new release.
=> API chapter 1

catt/cli.py
:dancer: :beer: 
EDIT: **redundant** :smile:
=> Minor stuff

catt/cli.py, catt/util.py
=> Unclutter cli.py a bit by moving subtitle stuff to util.py

catt/util.py
=> Use glob in hunt_subtitle

catt/api.py
=> Api polish

catt/cli.py, catt/stream_info.py, catt/util.py
Howdy
I've moved a bit more stuff to ```util.py```.
Also, I have returned ```hunt_subtitle``` to its original state, as my new implementation was lame and did not work as intended. Because of the casesensitivity problem of ```Path.glob```, I couldn't figure out how to fix my code in a sane way (sorry about not testing this properly).
Finally, current master is in a release-worthy state, so please consider making a release. One thing to note though, is that I intend to rework exceptions, which might lead to changes that break the "stable" API.
=> Small cleanup

catt/cli.py, catt/stream_info.py
..so it is possible to add a video id from a mixed video/playlist url to the queue.
Please consider making a release. The ability to cast a yt playlist without the lame procedure of adding video ids one by one is pretty neat.
=> Relax url validation in add cmd a bit

catt/api.py, catt/controllers.py
=> Use namedtuples instead of dicts for app_info

setup.py
..as a temporary fix for format selection syntax changes.
=> Pin ytdl requirement to 2019.1.17

catt/controllers.py
I incorporated half of your suggestion into this PR. :smiley: I also fixed a bug introduced in the previous PR.
=> Fix and simplify get_app

catt/api.py, catt/cli.py, catt/controllers.py, catt/error.py, catt/stream_info.py, catt/util.py, realcc_tests/test_procedure.py
Heyhey
Here's my proposal for a more useful organizing of exceptions. Not perfect, but definitely an improvement IMO.
I've had to implement the mechamism that transforms exceptions into cli error messages myself, now that we don't have the convenience of ```click.ClickException``` at our disposal anymore (which I have ditched, as the main idea here is that all of our own exceptions inherit from the same base class).
I've also had to slightly rework some of the subtitles stuff, to make it fit the ideas of this PR.
=> Exceptions rework

catt/cli.py, catt/util.py, realcc_tests/test_procedure.py
Howdy :cowboy_hat_face: 
I've improved the test procedure a bit, so that we do not engage in testing if any of the specified device names are incorrect. This led me to do a few changes/improvements to ```cli.py```.
=> Some testing stuff

catt/controllers.py
=> Use app id constants from pychromecast.config instead of our own

catt/cli.py
=> Add some missing params in yt-specific cmds

AUTHORS.rst, LICENSE, README.rst
..and some other details. :tv:
=>  Add "thanks" section to readme

CHANGELOG.md, catt/http_server.py, realcc_tests/test_procedure.py
I've also added some local file casting tests to what remains of my old testing scheme, just in case :smiley: 
I've run both the old and the new testing schemes, and we should be ready for release.
=> Improvements to test_procedure

CHANGELOG.md, catt/cli.py, catt/controllers.py, catt/error.py, catt/stream_info.py, catt/subs_info.py, catt/util.py
fixes #199
This turned out to be a bit more work than I anticipated, but the previous approach just didn't cut it anymore.
=> feat: Add ability to use subtitles with remote content

CHANGELOG.md, catt/api.py, catt/cli.py, catt/controllers.py, catt/http_server.py, catt/stream_info.py, catt/util.py
=> Late summer cleaning

CHANGELOG.md, catt/controllers.py
=> fix: Fix namespace related crash when using DashCast

catt/controllers.py, realcc_tests/test_procedure.py
..and a little test. :desktop_computer:
=> Refactor of namespace fix

catt/cli.py
Please make a release one of these days, as we've fixed a crash bug.
(and yes, I misspelled extravaganza :stuck_out_tongue: )
=> Release name for 0.10.x series

README.rst
=> Clarify installation instructions

.gitignore, catt/stream_info.py
(and an update for the gitignore) :tv:
=> Mixcloud fix

CHANGELOG.md, catt/cli.py, realcc_tests/test_procedure.py
=> feat: Add block option to cast cmd

CHANGELOG.md, catt/cli.py, catt/controllers.py
..as a workaround for devices not responding to stop cmd under certain circumstances.
fixes #236
=> feat: Add force option to stop cmd

CHANGELOG.md, catt/cli.py, catt/controllers.py
:tv: :cowboy_hat_face: :notes:
=> feat: Add play_toggle cmd

CHANGELOG.md, README.rst, catt/cli.py
:tv: :cowboy_hat_face: :guitar:
=> feat: Add cmds for config file manipulation

CHANGELOG.md, catt/cli.py, catt/controllers.py, catt/util.py
=> Misc cleaning

catt/cli.py
=> Make new config cmds work with ip as device arg

catt/stream_info.py, tests/test_catt.py
..which sometimes cause tests to fail on CI.
fixes #248
=> Mitigate "Too Many Requests" yt errs

setup.py
Update youtube-dl, PyChromecast, click, ifaddr, and requests to the latest versions, fixing broken casting of Twitch.tv
=> Update requirements to latest versions

requirements_dev.txt
And of course the commit that finally fixes CI is the one where I get tired of polluting master and decide to make a new branch.
=> Ignore pre-commit for non-3.7 Pythons

CHANGELOG.md, catt/api.py, catt/cli.py, catt/controllers.py, catt/stream_info.py, setup.py, tests/test_catt.py
..with no cache! (only marginally slower than before)
Let me know what you think.
=> Pychromecast 7.5 compat

catt/api.py, catt/cli.py, catt/controllers.py, catt/discovery.py
As promised :camel: :camel: :camel: :camel: :camel: :camel: :camel: :camel: :camel:
=> Move discovery stuff to separate file

catt/cli.py
fixes #253
The problem with the previous approach to getting config data into `click`, was that once the device info reached the subcmd, there was no way for it to tell whether it came from the cli or the config.
With this new approach we can do just that, and so I`ve made it mandatory to specify the device as a cli option, whenever the user wants to manipulate the config file. Not exactly what you asked for :smiley: , but I think that this is pretty clean UX.
=> Rework verification of cli option device

catt/controllers.py
I've moved the inactivity check to setup_cast where it belongs, and also made setup_cast less clunky.
=> Improve setup_cast

CHANGELOG.md, catt/cli.py, catt/discovery.py
:man_dancing: :woman_dancing: :man_dancing: :woman_dancing: :man_dancing: :woman_dancing: :man_dancing: :woman_dancing:
=> Don't do discovery dance when checking ip validity

CHANGELOG.md, catt/discovery.py, setup.py
Yo yo yo, pychromecast breakage fixed!
fixes #324
=> Pychromecast9

catt/controllers.py, setup.cfg
Fixes #343 
:loudspeaker: :loud_sound: :loudspeaker: :loud_sound: :loudspeaker: :loud_sound:
=> Allow use of info cmds on idle/inactive cc

catt/api.py
This will allow the possibility to init the media controller with a title, current_time and a thumb
=> refactor: Pass extra args to the media controller

catt/discovery.py
Some `pychromecast` changes I missed...
Given that specifying a device with an ip-address is broken in `0.12.8`, you should make a new release again. Sorry about that.
fixes #402
=> fix: Rework broken get_cast_with_ip

catt/cli.py
Resolves #440 (https://github.com/skorokithakis/catt/issues/440)
=> fix(save): Replace cst.media_info with cst.cast_info in save function
