catt/cli.py, catt/controllers.py
Howdy. A few further improvements here: "volumeup" and "volumedown" for incremental volume change, useful for keyboard-shortcuts and the like. And "info" for a complete dump of the contents of  cast.media_controller.status, which I think would be useful for testing/debugging purposes.
=> Add additional volume and info methods

catt/controllers.py
Howdy. A while back I gutted play_media of the checks we are doing now, to see if they were actually making a difference. It turns out they are not. I have had no failure in this period with this gutted version of play_media. I am pretty sure that, as long as we exclusively are using the 'Default Media Receiver' for playback, no blocking could occur.
=> Remove unnecessary code from play_media

catt/cli.py, catt/controllers.py, setup.py
Howdy. As promised, here's the config.
There's a few things to consider with this PR:
I've had to change my strategy with regards to [this problem](https://github.com/pallets/click/issues/456#issuecomment-159543498), in order to make reading values from config into defaults work. Which also means that I've had to alter `entry_points` in `setup.py`.
Also, I realize that the code in `cli()` is suboptimal, as it is not the proper click-esque way of solving the problem, with raising that exception directly in the code. And I've been unsure as to whether I should pass the device value directly to `writeconfig()` from `cli()`, or to use the `pass_obj` decorator. I've chosen the latter, as for now, we can write ctx.obj to disk, as is.
=> Add config

catt/controllers.py
Another small fix
In case you are planning on doing a release one of these days, I have two more minor PR's coming up:
+ Slight cleanup in `controllers.py`
+ Remove volume default in `cli.py`
=> fix: Make catt exit nicely if ytdl does not find a video.

catt/cli.py
`volume` should expect an argument, so I removed the default.
=> fix: Remove volume default.

catt/cli.py, catt/controllers.py, setup.py
Howdy.
So I worked around the issues and made this work almost perfectly (see notes).
With this PR, `catt` will now fail if nothing is playing (except `cast` of course), whereas before, you could do `catt ffwd 50` when nothing was playing, and `catt` would just exit quietly. The failling behaviour could also be useful in scripts.
Fixes #12 
EDIT: ready to merge
=> fix: Make catt work with pychromecast 0.8.0

catt/cli.py, catt/controllers.py
Now that we are using `pychromecast 0.8.0`, we can make use of a new feature: The ability to supply a delta to `volume_up` and `volume_down`. I have also used the opportunity to make the type of the value consistent with what we are using in `volume`.
=> feat: Add argument to volumeupdown

catt/controllers.py
Hi. So while experimenting with listeners, I found out that `catt cast` does not work if run when the cc is already playing something (in an app other than the "Default Media Receiver"). I discussed this briefly with the friendly pychromecast people: https://github.com/balloob/pychromecast/issues/168
So I did my own listener that sets its own event, to use instead of `block_until_active` in `CastController.play_media`. I realize that this is getting a bit involved, but as you can see in the before mentioned discussion, `block_until_active` simply does not cut it in it's current form, for use in `CastController.play_media`.
EDIT: Sorry about the extra commits, my own flake8 did not complain about import order. And now CI is failing on python3, I have no idea why (the branch installs fine).
=> fix: Further improve play_media

catt/controllers.py
Hi. Just a little adjustment, so that the output of `status` is consistent with the time descriptions the user can use with `seek` etc.
=> feat: Make status use regular time descriptions

catt/controllers.py
Howdy.
So the zeroconf/netifaces issues were resolved, giving us the opportunity to make CI builds pass once again. Running flake on `controllers.py` resulted in:
```
controllers.py:211:13: E731 do not assign a lambda expression, use a def
```
so I obeyed its command.
=> fix: Turn human_time into a def

catt/controllers.py
This is probably not going to make any difference in real use, but IMO it is better to register the listener before calling `media_controller.play_media`. With the current implementation there is a (very) slight chance that `self.listener.ready.wait()` will lock indefinitely.
=> Another slight improvement to play_media

catt/controllers.py
Here's a link that makes `catt` crash: http://www.gdcvault.com/play/1014846/Conference-Keynote-Shigeru
I'm not entirely shure we need to check for `ExtractorError`, but best to leave it there.
=> Handle extractor fail

catt/cli.py, catt/controllers.py
Since the youtube controller currently does not support selecting which playlist entry to play, I thought that a simple `skip` command would be useful. When casting a youtube playlist this would make the app play the next entry (if any). The implementation is a bit of a hack, but it seems to work well.
=> Add skip command

catt/controllers.py
Howdy.
So while tinkering with pychromecast in IPython I discovered something weird. It turns out that the cc info gathered when creating `Chromecast` objects differ, depending on whether you create it "manually" with an IP-adress or via auto-discovery. Pychromecast retrieves info via both zeroconf and DIAL, and those are unfortunately not exactly the same. The DIAL info is always retrieved. However when you use auto-discovery, the info retrieved via zeroconf overrides the DIAL info.
Please see: https://github.com/balloob/pychromecast/blob/master/pychromecast/__init__.py#L141
And thats a problem with regards to `catt` trying to determine cc model, because `model_name` might differ, depending on whether we use a cached ip or use auto-discovery. Thus this PR.
From my CC2:
```
In [2]: cast = …
```
=> Ensure DIAL info from all CC's

catt/controllers.py
Hi. I think I took the wrong approach in my last PR, with regards to ensuring DIAL info.
In this PR, we take action in `get_chromecasts` instead of the `CastController` constructor. This also has the added benefit of making `catt scan` return DIAL info, which will be useful if users report back with information about 4K-capable devices.
=> Ensure DIAL info in get_chromecasts

catt/stream_info.py
Hey. With YouTube offering audio-only DASH streams, we can utilize `StreamInfo` to enable this for audio devices, saving users a bit of bandwith.
=> Make audio devices stream DASH-audio from YouTube

catt/stream_info.py
Howdy.
After doing a bit of research I discovered that quite a few services offer DASH audio-only streams, so it makes more sense to always attempt extraction of such when casting to an audio device.
=> Further improve casting to audio devices

catt/stream_info.py
Hi. Youtube-dl already does fallback format selection, so no need for us to implement that.
=> Further improve format selection

catt/stream_info.py
Hey. A little 60fps tweak for twitch live streams (and content where framerate is reported by the extractor) on regular cc's.
It would be nice if you could make a release so that users can benefit from the YouTube functionality.
=> Improve standard format

catt/controllers.py
A few minor fixes for yt queue. 
The crash would occur if the user where to interrupt the yt-app while ```catt``` is trying to add several videos to the queue. 
Listener event flags are now set independently, as this is more correct and might otherwise lockup ```catt.add``` if interrupted while waiting for ```listener.not_buffering``` to be set (I honestly don't remember why I made ```not_buffering``` dependant on ```app_ready```).
=> Fix youtube add

catt/stream_info.py
Some playlist extractors (like ```bandcamp:album```) does not provide an ```id``` key with entries, so we need to tolerate that. Not really a problem, as ```_playlist_items``` only is needed by custom controllers.
=> Fix for StreamInfo.init

catt/controllers.py
Values for "volume_level" and "volume_muted" in ```cast.media_controller.status``` are useless (always the same). We now add the data from ```cast.status``` which contain the same volume keys, but with the corresponding values containing actual state.
=> Make info command more useful

catt/controllers.py
I've ditched my previous attempt of solving this, and made a decorator that catches the namespace errors that is thrown when the cc app is interrupted while we are waiting for a particular state (such as not buffering).
While tinkering with this, I managed to get the YouTube controller to throw an "Don't add videos while we're buffering" exception. So I've split the listener into discrete "cast" and "media" parts, and that actually seems to have made things a bit more stable (the previous approach might have caused threading issues).
=> Proper fix for add action

catt/cli.py, catt/controllers.py, setup.py
This should be the last PR for now.:sweat_smile:
+ I've made ```CastController.cast``` private, now that ```cli.cast``` only needs the cc name.
+ Made ```CastController.skip``` a bit prettier, no real change.
+ Freezed PyChromecast requirement, now that their next release will break Py2 support.
+ Minor change in how we display volume in ```status```, because of weird behaviour from PyChromecast 
with regards to this (try ```catt info``` after you've adjusted volume).
I hope you don't mind me rolling this up in one PR, but I wanted to move on.
PS: I've temporarily ditched my efforts to implement a verbose option, as it breaks tests, and I honestly can't figure out how to fix them.
=> Cleanup n freeze

catt/controllers.py
(Yes, I'm procrastinating. :innocent:)
Recently my chromecast has begun reporting a duration of zero, with some content (that is seekable) from a local streaming outfit, meaning that `status` is not useful with these.
I taken this opportunity to make ```catt``` fail when the user tries to seek content, where it makes no sense.
=> Make seek/status commands more useful with weird stream data

catt/controllers.py
Forgot about this. Otherwise a duration of zero would make for a screwy ```status``` readout.
=> Adapt status to possibility of bogus duration

catt/cli.py, catt/controllers.py, catt/stream_info.py
I've moved the check to ```cli.cast```, as that makes more sense. Otherwise, the ```play_playlist``` method of any custom controller would have to implement the check. While working on this, I came across a bug in ```stream_info``` that would make ```catt``` crash with empty playlists, so I fixed that.
=> Saner empty playlist check

catt/cli.py
=> Fix readconfig failing on py <3.6

catt/cli.py, catt/controllers.py
To make your weekend even more fun, here is a small PR to make `catt` cast images as well :)
yes, I am very optimistic you will soon merge my other PR so I not separating this one, for it will cause conflicts
=> fix: Specify the correct mimetype when casting local files

catt/controllers.py, catt/stream_info.py, setup.py
fixes #99
Currently, ```netifaces``` and ```requests``` are not in our install requirements. Should they be, now that we are importing them ourselves?
=> fix: Use netifaces instead of socket for get_local_ip

README.rst, catt/cli.py, catt/controllers.py, catt/stream_info.py
In another step to make `catt` cast ALL the things, here is a simple PR to make it cast any website to Chromecast.
The heavy lifting is done by DashCast ( http://stestagg.github.io/dashcast/ ), which was easier than I thought to implement on `catt` because `pychromecast` already supports it.
I decided not to change the UI by falling back to `dastcast` every time `youtube-dl` can not handle a URL.
That means you just needs to type:
`catt cast https://www.github.com/` 
to see github on your chromecast!
`catt info` shows the title of the webpage that is being displayed.
=> Support to Cast Any Website to Chromecast (via DashCast)

catt/controllers.py
This might sound like a silly idea, but it could be useful as a fallback for sites with autoplaying content that is not supported by ```youtube-dl```.
=> fix: Make dashcast work with audio devices

catt/cli.py
PS: ```flake8-import-order``` and ```isort``` do not agree on import order.
=> Make cast_site accept stdin as argument

catt/cli.py, catt/controllers.py
```is_file``` also fails if the file does not exist.
=> Use Path.is_file instead of Path.exists in file checks

catt/cli.py, catt/controllers.py
A few improvements:
+ We now fail with the correct error message, if the user tries ```catt restore```, without any config dir save file having been created.
+ I've made an attempt at making the create dir/file logic less flakey.
=> fix: Make save restore more robust

catt/stream_info.py
..id's and thumbnails were not returned for active playlist entries.
The missing id could only be triggered by something like:
```catt cast -r 'https://www.youtube.com/watch?v=CIvzV5ZdYis&list=PLQNHYNv9IpSzzaQMuH7ji2bEy6o8T8Wwn'```
I've added this to my testing scheme now.
=> Fix bug introduced in latest StreamInfo refactor

.pre-commit-config.yaml, catt/controllers.py, catt/stream_info.py, setup.py, tests/test_catt.py
We are now assuming that 1st/2nd gen. chromecasts are the only kinds of devices that report different names via DIAL/zeroconf.
fixes #119
Please test, as I do not have access to multiple audio devices myself.
=> Group support

catt/controllers.py
It occurs to me that we would have to do something like this, for this to be safe. Or just check for all possible attributes of the enum and then do ```else fail```, like I did before. Is there any convention/best practice when doing this kind of stuff in python?
=> Make use of enums in CastState even safer

catt/controllers.py, setup.py
The Dashcast/```cast_site``` functionality currently relies on a [hack](https://github.com/skorokithakis/catt/pull/102#issuecomment-390633433), in order for repeated uses of ```cast_site``` to work.
Marcosdiez submitted a PR to Pychromecast, that was merged, and now has been included in the new ```2.3.0``` release.
=> Dashcast update

catt/cli.py, catt/controllers.py
Currently, an entry in a save file is tied to a specific device, which means that the save file can't be used elsewhere. I've tried to fix that, while keeping backwards compability with existing save files.
We still use real device names in ```~/.config/catt/state.json```.
=> Make save files portable

catt/controllers.py, catt/stream_info.py, setup.py
```zeroconf``` have switched from ```netifaces``` to ```ifaddr``` (which, unlike ```netifaces```, is pure python), thus this PR.
```ifaddr``` is very simple though, and does not offer a means of identifying what interface the system considers to be the default, so I've attempted to implement something that returns the same(ish). Seems to work on Linux, but am not shure about macOS and Windows.
=> Switch from netifaces to ifaddr for get_local_ip

catt/stream_info.py
We now use format filters specified by the user e.g. ```catt cast -y "format=[format_id=480p]" <url>```.
=> User format

catt/controllers.py, setup.py, tests/test_catt.py
Because of my earlier "fix", the wrong ```CastController``` was being returned if the Dashcast app was running on the cc. Resulting in irrelevant error messages when issuing a control command (which the dashcast ```CastController``` does not support).
The CI failure is still because of the DailyMotion extractor, which was fixed in the latest release of ```youtube-dl```. Any ideas? Or should we just update requirements?
=> fix: Give correct error messages with Dashcast

README.rst, catt/cli.py
..as ```click``` (7.0+) has begun replacing underscores with dashes in command names that are derived from function names.
This was the cause of the confusion in #131, something I didn't pick up on, as it's been ages since I've last used the ```write_config``` command.
You should consider making a release, to avoid further confusion.
=> fix: Correct cast_site and write_config command names

catt/cli.py, catt/controllers.py
After a recent cc firmware upgrade, the behaviour of the cc after end of playback has changed if such a way, that the extra ```stream_type``` check in ```is_idle``` is no longer reliable. So I've resorted to a solution that Google can't break.
Also, I've introduced a new ```prep_info``` method so ```info``` and ```status``` commands are always available (as long as the cc is active).
Finally, I've sneaked in a slight improvement to url validation in ```cli.add```, in an attempt to weed out a few scenarios with irrelevant error msgs.
=> Prep method fixes

catt/cli.py
This bug is present in the latest release, as it has been hiding since ```--ytdl-option``` was implemented. Using custom ytdl opts only makes sense when using the default ctrl, as it's the only one where we get to choose the stream used.
=> fix: Make use of --ytdl-opt imply --force-default

catt/controllers.py, setup.py
Update youtube-dl requirement past ```2019.1.23``` that had broken format selection. (fixed in [```2019.1.24```](https://github.com/rg3/youtube-dl/releases/tag/2019.01.24))
also fixes https://github.com/skorokithakis/catt/issues/164, another (:face_with_head_bandage: ) bug introduced in the ```get_app``` changes.
=> Prepare for 0.9.2 release

catt/cli.py
Something that has annoyed me for a long time, but I was to lazy to fix.
Also works with cmd help!
=> Add -h alias for --help option

catt/stream_info.py
With "name your price" or free content, you can stream hi-res formats from Bandcamp, some of which are not supported by the cc audio (normally there's only the preview stream, which is mp3-128kb).
=> Add format hack for free Bandcamp content

catt/controllers.py
This passes both testing schemes, so is ready to merge. And it is definitely an improvement over the previous approach.
:guitar: :violin: :musical_keyboard:
=> fix: Try to eliminate spurious error msgs when seeking

CHANGELOG.md, catt/cli.py, catt/controllers.py, catt/util.py, realcc_tests/test_procedure.py, tests/test_catt.py
Howdy! :cowboy_hat_face: 
This won't work with audio device groups, as the "group leader" is on a different port.
It should be easy to add a `--port` option. I'll implement that as soon as I get my hands on another cc audio, so I can test.
fixes #196
=> feat: Add ability to use ip-address as device argument 

CHANGELOG.md, catt/cli.py
:face_with_head_bandage: I completely missed this one.
Ever since I did the api work, `get_chromecast` no longer throws anything, if supplied with name of non-existent cc, which we have relied on in `write_config`. But fixed now...
=> fix: Adapt write_config to "new" get_chromecast

CHANGELOG.md, catt/cli.py, catt/http_server.py, catt/stream_info.py, realcc_tests/test_procedure.py
:art: 
Server threads now die after having served an image or subtitles file once, so we only block the shell when strictly necessary.
=> fix: Only serve files forever if it is necessary

CHANGELOG.md, catt/api.py, catt/controllers.py, catt/stream_info.py, tests/test_catt.py
Howdy
For some time now, Google devices have stopped providing manufacturer/model_name info through DIAL, breaking our device type detection stuff in `StreamInfo`. So I've implemented a change to our caching, so we cache all the info we need from zeroconf. This work also turned out make some code a bit leaner.
PS: Your changelog thingy is indeed out of control :smile:
=> Cache zeroconf device info

requirements_dev.txt, setup.py
..to fix zeroconf issues
As it turns out, the problem was with `PyChromecast`s way of utilizing `zeroconf`, and not with `zeroconf` itself. Fixed in `4.1.1`.
Please make a release, so new users are not affected by this.
fixes #226
:cowboy_hat_face:
=> Update PyChromecast requirement

catt/stream_info.py
..when casting local files or direct urls.
Previous code never worked as I intended it, which was to show bare filename sans file-extension.
=> Fix filename display

catt/cli.py
This fixes #251, though I am still confused as to why the config dir might not exist.
=> Create parent directories if config dir doesn't exist (fixes #251)

catt/controllers.py, setup.py
Pychromecast 7 has a breaking change, with the return type of the
get_chromecasts function changing to also return a browser.
I ran black over this file but for me it changes a lot more of the formatting - happy to do that but wanted to check (and also at least isolate the actual change made to make it clearer). Also running tests locally seemed to be trying to do things to my actual chromecasts (?) so I thought I'd leave that for travis.
Deals with issue #271
=> fix: Force pychromecast 7, update to new api

catt/http_server.py
Fix byte range assert to test for 'is not None', to avoid breaking on ranges starting zero
Properly fixes #279
=> Fix byte range assert to test for 'is not None'

CHANGELOG.md, catt/api.py, catt/util.py
For your consideration, a subtitle parameter to the API call.
I'm not sure whether it should be called `subtitle_url`, though, I'm not sure if it has to be a URL or if it can be a path.
=> feat: Add remote-only subtitles to the API

catt/cli.py
The current 10 second wait isn't long enough on slow networks (like my wifi network at home!). Let's wait 30 seconds instead.
Fixes #294.
I was unable to reproduce the issue again with the 10 second wait (typical!), but I was able to repro by setting the timeout *lower*.
Thanks!
=> fix: Increase timeout for the Chromecast to connect to the HTTP server

catt/cli.py, catt/controllers.py, realcc_tests/test_procedure.py, tests/test_catt.py
fixes #286 :horse_racing: :horse_racing: :horse_racing:
=> Cast 'n' seek

CHANGELOG.md, setup.py, tests/test_catt.py
CI installs Click 8, which doesn't work in 3.5. This PR limits the dependencies so we only use 7.x.
=> Hopefully fix CI

README.rst
Given docker example would not work, because container is put in its own network, where are no devices. Forcing docker to join host network allows it to see devices. Also `--rm` added, so that example will be deleted as soon as it is executed.
=> fix docker example

CHANGELOG.md, catt/cli.py
This fix allows device names to be specified in mixed case, but keeps aliases case-insensitive (issue #375). I didn't add any automated tests since they would require specific Chromecast device names to really work, but I did some manual testing:
catt.cfg:
```
[aliases]
test1 = Bedroom TV
TEST2 = Chromecast_2
```
Tests:
```
catt -d "Bedroom TV" status
Volume: 100
catt -d test1 status
Volume: 100
catt -d Test1 status
Volume: 100
catt -d test2 status
Error: Specified device "Chromecast_2" not found.
catt -d Test2 status
Error: Specified device "Chromecast_2" not found.
catt -d "Bedroom TV" set_alias Test3
catt -d "Bedroom TV" set_default
catt -d TEST3 status
Volume: 100
```
catt.cfg after:
```
[aliases]
test2 = Chromecast_2
test3 = Bedroom TV
[options]
device = Bedroom TV
```
=> Fixed casing issue with device names (#375)

catt/cli.py
The importlib.metadata used to live as importlib_metadata, this try…except will make catt runnable on older installations
=> Catching the ImportError on systems running Python versions older than 3.8

pyproject.toml
fix included in `pychromecast 12.1.4`
=> Remove redundant protobuf requirement

catt/stream_info.py, pyproject.toml, realcc_tests/test_procedure.py
Originally reported in #376.
Casting of direct media urls seem to work again, so I updated the `yt-dlp` requirement.
fixes #367
=> Fix youtube playlist issues

catt/api.py
The path to get the ip from pychromecast is now c.socket_client.host
=> Fix discovery function

README.md
This updates the README to document the config path as ~/Library/Application Support/catt/catt.cfg. It does not read from ~/.config/catt/catt.cfg on macOS.
=> doc: Document macOS config path in README

catt/api.py, catt/cli.py, catt/controllers.py, catt/util.py, realcc_tests/test_procedure.py
With this addition, CATT should now have the ability to toggle between mute states while automatically preserving the previous volume level. This function will also prevent a volume preview tone on some devices.
Example: `catt -d <DEVICE_OR_IP> volumemute <true | false>`
Note that the default value is `true`.
_Not exactly._ I also have a Lenovo Smart Display. While that device mutes and unmutes as expected, it unfortunately still emits a volume tone.
I only have the two device models, so feedback on which brands are/are not working would be great. I suspect it to be the same as Home Assistant's `media_player.volume_mute` service.
=> Add volumemute command

pyproject.toml
The project seems to use poetry to manage its dependencies, and defining the build-system allows building it using the generic `build` frontend, which distros heavily rely on.
See https://github.com/python-poetry/poetry-core#usage.
=> fix: set explicit build-backend

pyproject.toml
Update pychromecast to 14.0.1
During my testing I found no issues, but I only cast the HA dashboard...
So nothing fancy.
=> chore: updated pychromecast dependency

catt/cli.py, catt/controllers.py, catt/stream_info.py
Hello and thank you for this Python library! This is my first PR in this repo.
I started hacking away in order to fix what appeared to be a bug on my end: every time I tried to cast a video from YouTube using the default video application (not the YouTube app, in order to skip ads), it was detected as a live stream. Because of this, CATT wouldn't allow me to save the state of the video, or skip backward and forward. Because of this, I didn't create an issue in GitHub to ask for an opinion.
I don't remember this happening from the start, and it might simply be a weird default at PyChromecast. Anyways, CATT should have an extra function now.
I couldn't get CATT to work with an actual YouTube video live stream (even after discarding all my changes), so I tested it with using regular YouTube …
=> Tell apart live videos from buffered videos
